### ISSUE TITLE
Documention for IMIS template and iPARTS in Reactjs 

### ISSUE THREAD

**Issue by Crelloc** [Advsol/Innovations20019-react-starter#1]
Hey, Do you have any reference or documentation or personal notes on implementing reactjs with IMIS to create a custom template and to create custom iParts with reactjs?

You have this starter kit but how do you integrate it?

Thanks

**Comment by RoboAndie** [comment]
Hi Thomas,
We have documentation on creating client-side iParts available here: https://developer.imis.com/docs/developing-a-client-based-ipart

Does that get you what you need?

Thanks,
Andrea

**Comment by Crelloc** [comment]
Yes I’ve noticed that documentation.

I was hoping to see a code example on how to integrate reactjs to iMIS & iParts for reference.

I don’t have access yet to an iMIS account to begin testing code.


>

**Comment by RoboAndie** [comment]
These steps should apply to any front-end technology, including reactjs. Once you get access to an iMIS system, if you run into any specific issues, please reach out to our developer forum here: https://developer.imis.com/discuss - this is a much more active forum for technical questions.

Thanks,
Andrea
